services:
  - type: web
    name: lms-web
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    healthCheckPath: /health
    preDeployCommand: flask db upgrade
    envVars:
      - key: SECRET_KEY
        value: ""
      - key: DATABASE_URL
        value: ""
      - key: FLASK_ENV
        value: "production"
      - key: MAIL_USERNAME
        value: ""
      - key: MAIL_PASSWORD
        value: ""
      - key: ZOOM_ACCOUNT_ID
        value: ""
      - key: ZOOM_CLIENT_ID
        value: ""
      - key: ZOOM_CLIENT_SECRET
        value: ""
      - key: SENTRY_DSN
        value: ""
